/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Asia/Dubai';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'settings-audit': SettingsAudit;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'settings-audit': SettingsAuditSelect<false> | SettingsAuditSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'brand-copy': BrandCopy;
    'booking-settings': BookingSetting;
    'template-copy': TemplateCopy;
    'seo-defaults': SeoDefault;
    'payment-settings': PaymentSetting;
    'email-settings': EmailSetting;
    'invoice-settings': InvoiceSetting;
    'notification-settings': NotificationSetting;
    'analytics-settings': AnalyticsSetting;
    'system-state': SystemState;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'brand-copy': BrandCopySelect<false> | BrandCopySelect<true>;
    'booking-settings': BookingSettingsSelect<false> | BookingSettingsSelect<true>;
    'template-copy': TemplateCopySelect<false> | TemplateCopySelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'payment-settings': PaymentSettingsSelect<false> | PaymentSettingsSelect<true>;
    'email-settings': EmailSettingsSelect<false> | EmailSettingsSelect<true>;
    'invoice-settings': InvoiceSettingsSelect<false> | InvoiceSettingsSelect<true>;
    'notification-settings': NotificationSettingsSelect<false> | NotificationSettingsSelect<true>;
    'analytics-settings': AnalyticsSettingsSelect<false> | AnalyticsSettingsSelect<true>;
    'system-state': SystemStateSelect<false> | SystemStateSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      noop: TaskNoop;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Who can sign in to this admin, and what they may do. Invite colleagues rather than sharing passwords.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * As colleagues see it — in the enquiries 'assigned to' list, in the audit log.
   */
  name: string;
  /**
   * What this person may do. Only admins can change roles; the first account created is always an admin.
   */
  role: 'admin' | 'editor' | 'front-desk';
  /**
   * Untick to stop this person signing in without deleting their account or history.
   */
  active?: boolean | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photographs, the studio film, logos and PDF fonts. A file that is still used somewhere cannot be deleted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe what is IN the frame — never an occasion the photo does not show. Required unless the file is decorative.
   */
  alt?: string | null;
  /**
   * Tick for textures and backgrounds that carry no meaning. Alt text is then not required.
   */
  decorative?: boolean | null;
  caption?: string | null;
  credit?: string | null;
  /**
   * AI-generated and Unknown pictures cannot be published in hero or card slots unless Settings → Site details → Advanced allows it.
   */
  provenance: 'studio' | 'client-supplied' | 'stock' | 'ai-generated' | 'unknown';
  /**
   * Optional — where the stock licence is filed.
   */
  licence?: string | null;
  /**
   * Required before a photo of an identifiable child is published (brand rule).
   */
  consent?: boolean | null;
  tags?:
    | (
        | 'experience-hero'
        | 'experience-gallery'
        | 'programme'
        | 'venue'
        | 'gallery-make'
        | 'gallery-making'
        | 'gallery-keep'
        | 'logo'
        | 'og'
        | 'hero'
        | 'seasonal'
        | 'kids'
        | 'film'
        | 'font'
      )[]
    | null;
  sizeNotice?: string | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    menu?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    plate?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every change to a behaviour-changing setting, with who made it. Read-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-audit".
 */
export interface SettingsAudit {
  id: string;
  global: string;
  field: string;
  from?: string | null;
  to?: string | null;
  user?: (string | null) | User;
  at: string;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'noop';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?: ('inline' | 'noop') | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'noop') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'settings-audit';
        value: string | SettingsAudit;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  decorative?: T;
  caption?: T;
  credit?: T;
  provenance?: T;
  licence?: T;
  consent?: T;
  tags?: T;
  sizeNotice?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        menu?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        plate?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-audit_select".
 */
export interface SettingsAuditSelect<T extends boolean = true> {
  global?: T;
  field?: T;
  from?: T;
  to?: T;
  user?: T;
  at?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Name, logos, contact details, social links, newsletter. The Advanced section (site address, background tasks) is admin-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Appears in page titles, share cards and screen-reader labels.
   */
  name: string;
  /**
   * Printed after © in the footer. Invoices have their own copy under Invoices & VAT.
   */
  legalName: string;
  /**
   * One plain sentence used as the default meta description. Not the script tagline — that is Brand wording → Script tagline.
   */
  tagline: string;
  /**
   * Transparent PNG or SVG, at least 1000 px wide. Used over the hero and in share images. The ink box below is measured automatically when this changes.
   */
  logoOnDark?: (string | null) | Media;
  /**
   * Where the lettering sits inside the file, as shares of its width and height. Recomputed from the image's transparency each time the logo file changes; nothing to edit.
   */
  logoOnDarkInk?: {
    left?: number | null;
    top?: number | null;
    width?: number | null;
    height?: number | null;
  };
  /**
   * The header once it turns white, the footer, and invoices unless they set their own.
   */
  logoOnLight?: (string | null) | Media;
  /**
   * Tiny square mark next to the copyright line. SVG or square PNG.
   */
  monogram?: (string | null) | Media;
  contact?: {
    /**
     * One line per row, as it should print on the contact page and footer.
     */
    addressLines?:
      | {
          line: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Shown on the contact page and in the footer when set.
     */
    email?: string | null;
    /**
     * Printed as typed; the call link strips spaces. Include the country code.
     */
    phone?: string | null;
    /**
     * Digits only, country code first (9715XXXXXXXX). Leave blank to keep WhatsApp off the site.
     */
    whatsappNumber?: string | null;
    whatsappGreeting?: string | null;
    /**
     * e.g. “Sat–Thu” / “10:00–22:00”. Reserved for the venue plate and footer; nothing prints it yet.
     */
    hours?:
      | {
          days: string;
          hours: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Only rows with a URL are shown. Instagram and Facebook have icons; the others render as text links.
   */
  socials?:
    | {
        platform: 'instagram' | 'facebook' | 'tiktok' | 'youtube' | 'x' | 'linkedin';
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    /**
     * It only appears when this is on and a provider URL is set below.
     */
    enabled?: boolean | null;
    /**
     * The URL a Mailchimp, Klaviyo or Buttondown embed form posts to. The footer renders a plain form at it — no script.
     */
    actionUrl?: string | null;
    /**
     * What the provider calls the email field. Almost always “email”.
     */
    fieldName?: string | null;
    heading?: string | null;
    /**
     * A promise about what gets sent — say what the studio will actually send.
     */
    description?: string | null;
    cta?: string | null;
  };
  /**
   * The site's address, e.g. https://www.maisonpalettia.com — no path, no trailing slash. Changing it changes every canonical, sitemap URL, email link and Mamo Pay return URL, and the webhook must be re-registered under Payments.
   */
  publicUrl: string;
  /**
   * Sent to social networks as the page's language and region.
   */
  locale?: 'en_AE' | null;
  heroTheme?: {
    /**
     * Pages whose hero is dark, so the header starts in light ink.
     */
    darkRoutes?:
      | {
          /**
           * Starts with a slash, e.g. /checkout. A trailing * matches everything beneath.
           */
          path: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Pages whose hero is light, so the header starts in dark ink.
     */
    lightRoutes?:
      | {
          /**
           * Starts with a slash, e.g. /checkout. A trailing * matches everything beneath.
           */
          path: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Off hides the contact and private-event forms. Enquiries already received stay in the Inbox.
   */
  enquiriesEnabled?: boolean | null;
  /**
   * Confirmation emails, seat-hold expiry, payment checks, reminders. Turn off only when Nexeor asks you to — the dashboard shows a red warning while this is off.
   */
  jobsEnabled?: boolean | null;
  /**
   * Allow pictures marked AI-generated or Unknown origin in hero and card slots. Off blocks publishing an experience, session or programme whose main image is marked that way.
   */
  allowAiImagery?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * One list feeds the desktop bar, mobile bar, mobile sheet and footer. Order here is order everywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  /**
   * Three to seven items. Drag to reorder.
   */
  primary?:
    | {
        /**
         * Up to 16 characters on the desktop bar.
         */
        label: string;
        link: {
          type: 'internal' | 'external';
          url?: string | null;
          /**
           * Scrolls to a section, e.g. scheduled → /events#scheduled
           */
          anchor?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Which panel drops under this item on desktop. The panels' contents come from Experiences, Programmes and the About doors below.
         */
        menu?: ('none' | 'experiences' | 'private-events' | 'about') | null;
        mobileSurface: 'bar' | 'sheet' | 'none';
        /**
         * Falls back to the label. Up to 10 characters.
         */
        mobileShortLabel?: string | null;
        /**
         * Still shown in the footer and on phones.
         */
        secondary?: boolean | null;
        utility?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The one booking button in the header and the phone's Book tab.
   */
  primaryCta: {
    label: string;
    link: {
      type: 'internal' | 'external';
      url?: string | null;
      /**
       * Scrolls to a section, e.g. scheduled → /events#scheduled
       */
      anchor?: string | null;
      newTab?: boolean | null;
    };
  };
  /**
   * The three tabs every phone shows regardless of the list above.
   */
  bottomBar?: {
    contactLabel?: string | null;
    aboutLabel?: string | null;
    bookLabel?: string | null;
  };
  /**
   * The options list itself is built from scheduled experiences and open sessions; only the words around it live here.
   */
  bookSheet?: {
    heading?: string | null;
    lead?: string | null;
    anytimeNote?: string | null;
    anytimeLinkLabel?: string | null;
  };
  /**
   * The first link keyboard users reach; it jumps past the header.
   */
  skipLink?: string | null;
  experiencesMenu: {
    /**
     * Rows under each heading come from Experiences by kind.
     */
    groups?:
      | {
          kind: 'diy' | 'scheduled';
          title: string;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * The highlighted door at the end of the panel (today: Upcoming dates).
     */
    door: {
      title: string;
      sub?: string | null;
      link: {
        type: 'internal' | 'external';
        url?: string | null;
        /**
         * Scrolls to a section, e.g. scheduled → /events#scheduled
         */
        anchor?: string | null;
        newTab?: boolean | null;
      };
    };
    previewActionDiy?: string | null;
    previewActionScheduled?: string | null;
  };
  /**
   * Rows in the rail are the Programmes with “Show in menu” ticked.
   */
  privateEventsMenu?: {
    railTitle?: string | null;
    railNote?: string | null;
    previewEyebrow?: string | null;
    previewAction?: string | null;
    /**
     * Two doors: all programmes, and the enquiry form.
     */
    doors?:
      | {
          title: string;
          sub?: string | null;
          link: {
            type: 'internal' | 'external';
            url?: string | null;
            /**
             * Scrolls to a section, e.g. scheduled → /events#scheduled
             */
            anchor?: string | null;
            newTab?: boolean | null;
          };
          accent?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  aboutMenu?: {
    doors?:
      | {
          name: string;
          sub?: string | null;
          link: {
            type: 'internal' | 'external';
            url?: string | null;
            /**
             * Scrolls to a section, e.g. scheduled → /events#scheduled
             */
            anchor?: string | null;
            newTab?: boolean | null;
          };
          /**
           * The cut-out shape drawn on the door.
           */
          mark?:
            | (
                | 'splash'
                | 'coral'
                | 'starleaf'
                | 'bow'
                | 'zigzag'
                | 'cutout'
                | 'starburst'
                | 'wave'
                | 'bean'
                | 'slabCoral'
                | 'dot'
              )
            | null;
          id?: string | null;
        }[]
      | null;
  };
  mobile?: {
    privateEventsCta?: string | null;
  };
  /**
   * The “Why we do it” text is Brand wording → Mission; it is not repeated here.
   */
  footer?: {
    /**
     * Three columns look best; the grid takes one to four.
     */
    groups?:
      | {
          title: string;
          items?:
            | {
                label: string;
                link: {
                  type: 'internal' | 'external';
                  url?: string | null;
                  /**
                   * Scrolls to a section, e.g. scheduled → /events#scheduled
                   */
                  anchor?: string | null;
                  newTab?: boolean | null;
                };
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    findUsHeading?: string | null;
    studioHeading?: string | null;
    whyHeading?: string | null;
    followHeading?: string | null;
    policiesHeading?: string | null;
    directionsLabel?: string | null;
    policiesBlurb?: string | null;
    backToTop?: string | null;
  };
  /**
   * Add Privacy / Terms here once those policies exist — usually a link to a Policy marked “Show in legal row”.
   */
  legal?:
    | {
        label: string;
        link: {
          type: 'internal' | 'external';
          url?: string | null;
          /**
           * Scrolls to a section, e.g. scheduled → /events#scheduled
           */
          anchor?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  utilityBar?: {
    heading?: string | null;
  };
  /**
   * The popular-search chips are derived from categories, kinds and localities; only the words around them live here.
   */
  search?: {
    triggerLabel?: string | null;
    heading?: string | null;
    placeholderWide?: string | null;
    placeholderNarrow?: string | null;
    popularHeading?: string | null;
    sessionsHeading?: string | null;
    activitiesHeading?: string | null;
    viewAllLabel?: string | null;
    noResultsTitle?: string | null;
    noResultsBody?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sentences reused across pages (tagline, story, find-us line). Edit once, changes everywhere they appear.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-copy".
 */
export interface BrandCopy {
  id: string;
  /**
   * Set in the script face; keep it to one short line. Changes the About title, the footer and the homepage closing eyebrow together.
   */
  tagline: string;
  /**
   * One row per paragraph. The first sentence is also the About page's search description.
   */
  brandStory?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Homepage section 02 and the Gallery page opening.
   */
  openingStatement?: {
    heading?: string | null;
    body?: string | null;
    closer?: string | null;
    panel?: {
      heading?: string | null;
      body?: string | null;
      signOff?: string | null;
    };
  };
  /**
   * Printed at the foot of the homepage and of About.
   */
  closing?: {
    heading?: string | null;
    body?: string | null;
  };
  /**
   * About page Purpose card and the footer's “Why we do it”. The deck labels Mission/Vision the other way round; the brief's assignment is used.
   */
  mission?: string | null;
  vision?: string | null;
  purposeLabels?: {
    mission?: string | null;
    vision?: string | null;
  };
  community?: {
    heading?: string | null;
    body?: string | null;
    closer?: string | null;
  };
  /**
   * Three to six steps on About. The first two also feed the two doors on the Experiences page.
   */
  journey?:
    | {
        /**
         * Keep the first two as “walk-in-diy” and “scheduled-sessions”: the Experiences page quotes their descriptions.
         */
        slug?: string | null;
        name: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Four cards in a 2×2 grid on About.
   */
  whatSetsUsApart?:
    | {
        /**
         * A stable key for the card; renderers use it, visitors never see it.
         */
        slug?: string | null;
        /**
         * Set in capitals; keep it to 22 characters.
         */
        name: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Homepage, Experiences page, programme pages and event pages.
   */
  findUsHeading?: string | null;
  /**
   * FAQ, Locations page and two homepage sections. One sentence.
   */
  findUsLine?: string | null;
  /**
   * Experiences page and the homepage's two-roads section.
   */
  makeItYourWay?: string | null;
  /**
   * Private events page, programme pages, the enquiry form and the FAQ.
   */
  privateEventInvite?: string | null;
  /**
   * Under the programme list and in the Private events menu.
   */
  programmesNote?: string | null;
  /**
   * Printed on the FAQ and event pages. The DIY policy says premium materials may cost extra — keep the two in step.
   */
  everythingProvided?: string | null;
  /**
   * Used by any “Steps” section set to “Brand wording — private event steps”.
   */
  privateEventSteps?:
    | {
        title: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  seasonalIntro?: string | null;
  /**
   * Examples of past seasons, not a calendar.
   */
  seasonalMoments?:
    | {
        occasion: string;
        experience?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  littleCreators?:
    | {
        name: string;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  collaborations?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  experienceStatement?: string | null;
  ourApproach?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Anything from the brand deck worth keeping on record but not printing.
   */
  notes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * What a booking says, status wording, checkout/basket labels, ticket PDF text. The Bookings open/closed switch is admin-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings".
 */
export interface BookingSetting {
  id: string;
  /**
   * On: Book buttons go to checkout and Mamo Pay. Off: Book buttons show the message below and link to the contact page; staff can still create bookings at the desk. Switching on is refused until Email, Payments and the site address are set up.
   */
  bookingsOpen?: boolean | null;
  /**
   * Shown on every Book button and booking bar while bookings are closed.
   */
  closedMessage?: string | null;
  closedCtaLabel?: string | null;
  closedCtaLink: {
    type: 'internal' | 'external';
    url?: string | null;
    /**
     * Scrolls to a section, e.g. scheduled → /events#scheduled
     */
    anchor?: string | null;
    newTab?: boolean | null;
  };
  /**
   * One sentence, printed under the Confirm button, on the confirmation page and as the FAQ answer to “Am I charged when I book?”.
   */
  bookingTerms?: string | null;
  /**
   * Two to four capital letters, optionally ending in a hyphen. Every reference and the lookup hint start with it.
   */
  referencePrefix?: string | null;
  /**
   * At or below this many seats a session is flagged on the site and the low-seats staff alert fires.
   */
  lowSeatThreshold?: number | null;
  /**
   * Confirmation page, status lookup and emails. The colour is secondary; the word is always printed.
   */
  statusCopy?: {
    confirmed?: {
      label?: string | null;
      note?: string | null;
    };
    pending?: {
      label?: string | null;
      note?: string | null;
    };
    completed?: {
      label?: string | null;
      note?: string | null;
    };
    cancelled?: {
      label?: string | null;
      note?: string | null;
    };
  };
  purchaseConfirmedNote?: string | null;
  checkout?: {
    heading?: string | null;
    backLabel?: string | null;
    detailsHeading?: string | null;
    detailsLead?: string | null;
    /**
     * Shown when the details from the booking step were carried into checkout.
     */
    carriedOverNote?: string | null;
    confirmLabel?: string | null;
    confirmingLabel?: string | null;
    emptyTitle?: string | null;
    emptyBody?: string | null;
    emptyCta?: string | null;
    errorGeneric?: string | null;
    errorEmpty?: string | null;
    errorPassed?: string | null;
    errorFields?: string | null;
  };
  cart?: {
    heading?: string | null;
    addAnother?: string | null;
    removeLabel?: string | null;
    passedLine?: string | null;
    subtotalLabel?: string | null;
    totalLabel?: string | null;
  };
  /**
   * The small link in the header once something is in the basket.
   */
  basketLinkLabel?: string | null;
  passCodeCopy?: {
    label?: string | null;
    placeholder?: string | null;
    apply?: string | null;
    messages?: {
      empty?: string | null;
      unavailable?: string | null;
      invalid?: string | null;
      applied?: string | null;
    };
  };
  bookStep?: {
    heading?: string | null;
    lead?: string | null;
    backLabel?: string | null;
    steps?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    continueLabel?: string | null;
    openingLabel?: string | null;
    summaryError?: string | null;
    notesLabel?: string | null;
    passedTitle?: string | null;
    /**
     * {title} and {date} are replaced with the session's name and date.
     */
    passedBody?: string | null;
    passedCta?: string | null;
  };
  /**
   * /payment-success — the page a customer lands on after paying.
   */
  confirmation?: {
    heading?: string | null;
    viewEventsLabel?: string | null;
    checkStatusLabel?: string | null;
    notFoundHeading?: string | null;
    notFoundTitle?: string | null;
    /**
     * {reference} is replaced with the reference.
     */
    notFoundBodyWithRef?: string | null;
    notFoundBodyNoRef?: string | null;
  };
  /**
   * /booking-status — look up a booking by reference.
   */
  status?: {
    heading?: string | null;
    lead?: string | null;
    fieldLabel?: string | null;
    /**
     * {prefix} is replaced with the reference prefix.
     */
    placeholder?: string | null;
    /**
     * {prefix} is replaced with the reference prefix.
     */
    hint?: string | null;
    cta?: string | null;
    noneTitle?: string | null;
    noneBody?: string | null;
    noneCta?: string | null;
  };
  eventPage?: {
    bookLabel?: string | null;
    passedLabel?: string | null;
    perPersonLabel?: string | null;
    closedFullFact?: string | null;
    closedPassedFact?: string | null;
    noneOpenSuffix?: string | null;
    othersOpenSuffix?: string | null;
    seeOpenLabel?: string | null;
    diyTitle?: string | null;
    diyBody?: string | null;
    diyCta?: string | null;
    comingSoonNote?: string | null;
    readyHeading?: string | null;
    /**
     * The “everything provided” promise — keep it in step with the DIY policy's materials clause.
     */
    readyBody?: string | null;
    utilityNote?: string | null;
  };
  /**
   * The two product names appear in about twenty places; change them here once.
   */
  labels?: {
    createAnytime?: string | null;
    createTogether?: string | null;
    anyTime?: string | null;
    scheduled?: string | null;
    noBooking?: string | null;
    bookedOnline?: string | null;
    scheduledSession?: string | null;
    diyLine?: string | null;
    scheduledLine?: string | null;
  };
  utilityBars?: {
    /**
     * The note and links at the foot of every event page.
     */
    eventDetail?: {
      note?: string | null;
      links?:
        | {
            label: string;
            link: {
              type: 'internal' | 'external';
              url?: string | null;
              /**
               * Scrolls to a section, e.g. scheduled → /events#scheduled
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            id?: string | null;
          }[]
        | null;
    };
    /**
     * The note and links at the foot of checkout.
     */
    checkout?: {
      note?: string | null;
      links?:
        | {
            label: string;
            link: {
              type: 'internal' | 'external';
              url?: string | null;
              /**
               * Scrolls to a section, e.g. scheduled → /events#scheduled
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Printed on every QR ticket, under the session details.
   */
  ticket?: {
    heading?: string | null;
    instructions?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Fixed labels on event, programme and policy pages and the 404 page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "template-copy".
 */
export interface TemplateCopy {
  id: string;
  eventDetail?: {
    breadcrumbRoot?: string | null;
    whenTerm?: string | null;
    timeTerm?: string | null;
    durationTerm?: string | null;
    whereTerm?: string | null;
    priceTerm?: string | null;
    perPersonLabel?: string | null;
    howItRunsTerm?: string | null;
    statusTerm?: string | null;
    aboutHeading?: string | null;
    locationHeadingScheduled?: string | null;
    locationHeadingDiy?: string | null;
    directionsNote?: string | null;
    moreEventsHeading?: string | null;
    /**
     * Over the title when the experience has only this one date.
     */
    soloEyebrow?: string | null;
    soloCta?: string | null;
    upcomingDatesHeading?: string | null;
    waitlistHeading?: string | null;
    waitlistBody?: string | null;
    waitlistCta?: string | null;
    waitlistSuccess?: string | null;
  };
  programmeDetail?: {
    eyebrow?: string | null;
    activitiesHeading?: string | null;
    activitiesLead?: string | null;
    stepsEyebrow?: string | null;
    closeHeading?: string | null;
    ctaPrimaryLabel?: string | null;
    ctaSecondaryLabel?: string | null;
  };
  policyDetail?: {
    eyebrow?: string | null;
    backLabel?: string | null;
    closeHeading?: string | null;
    closeBody?: string | null;
    closeCta?: string | null;
  };
  /**
   * The doors' own titles and notes are on the Events page itself (page builder).
   */
  eventsBrowser?: {
    dateFilterLabel?: string | null;
    typeFilterLabel?: string | null;
    locationFilterLabel?: string | null;
    clearFilterLabel?: string | null;
    clearAllLabel?: string | null;
    emptyTitle?: string | null;
    emptyBody?: string | null;
    doorModeLabels?: {
      diy?: string | null;
      scheduled?: string | null;
    };
    datePassedLabel?: string | null;
    fullyBookedLabel?: string | null;
  };
  notFound?: {
    eyebrow?: string | null;
    /**
     * Use | to break the line, e.g. “This page has | wandered off.”
     */
    heading?: string | null;
    body?: string | null;
    cta?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Title template, default share image, robots rules.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: string;
  /**
   * %s is replaced with the page title, e.g. “%s · Maison Palettia”.
   */
  titleTemplate: string;
  /**
   * 1200×630, JPEG under 600 KB (WhatsApp drops larger previews). Leave empty to keep the generated logo card.
   */
  shareImage?: (string | null) | Media;
  twitterCard?: ('summary_large_image' | 'summary') | null;
  /**
   * Written into robots.txt. Checkout, confirmation and account pages belong here; never add “/”.
   */
  robotsDisallow?:
    | {
        /**
         * Starts with a slash, e.g. /checkout. A trailing * matches everything beneath.
         */
        path: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Test/Live keys, webhook, checkout options.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-settings".
 */
export interface PaymentSetting {
  id: string;
  /**
   * Test: Mamo sandbox, no real charges. Live: real payments. Switching to Live opens a checklist and is refused until every line passes.
   */
  mode: 'test' | 'live' | 'mock';
  provider?: 'mamo' | null;
  test?: {
    /**
     * Mamo Dashboard → Developer → Keys, in the sandbox account.
     */
    apiKey?: string | null;
    apiKeySetAt?: string | null;
    /**
     * Created by Register/Update webhook and Rotate webhook secret. Mamo sends it with every delivery so we can tell its calls from anyone else's.
     */
    webhookAuthHeader?: string | null;
    webhookAuthHeaderSetAt?: string | null;
    previousWebhookAuthHeader?: string | null;
    previousWebhookAuthHeaderSetAt?: string | null;
    previousValidUntil?: string | null;
    webhookId?: string | null;
    webhookRegisteredAt?: string | null;
    /**
     * Must start with the current site address. The dashboard flags “Webhook points at an old address” when it does not.
     */
    webhookUrl?: string | null;
    /**
     * { ok, at, message } from the last Test connection.
     */
    lastConnectionCheck?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Which request header Mamo actually used on the first verified delivery.
     */
    observedAuthHeaderName?: string | null;
  };
  live?: {
    /**
     * Mamo Dashboard → Developer → Keys, in the live account.
     */
    apiKey?: string | null;
    apiKeySetAt?: string | null;
    /**
     * Created by Register/Update webhook and Rotate webhook secret. Mamo sends it with every delivery so we can tell its calls from anyone else's.
     */
    webhookAuthHeader?: string | null;
    webhookAuthHeaderSetAt?: string | null;
    previousWebhookAuthHeader?: string | null;
    previousWebhookAuthHeaderSetAt?: string | null;
    previousValidUntil?: string | null;
    webhookId?: string | null;
    webhookRegisteredAt?: string | null;
    /**
     * Must start with the current site address. The dashboard flags “Webhook points at an old address” when it does not.
     */
    webhookUrl?: string | null;
    /**
     * { ok, at, message } from the last Test connection.
     */
    lastConnectionCheck?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Which request header Mamo actually used on the first verified delivery.
     */
    observedAuthHeaderName?: string | null;
  };
  checkout?: {
    linkType?: ('standalone' | 'inline') | null;
    paymentMethods?: ('card' | 'wallet')[] | null;
    enableTabby?: boolean | null;
    /**
     * Off: customers get our confirmation, invoice and tickets only.
     */
    sendMamoReceipt?: boolean | null;
    requireTerms?: boolean | null;
    /**
     * How long a basket keeps its seats while the customer pays. 3DS and wallets finish in minutes.
     */
    holdMinutes?: number | null;
    /**
     * Shown on Mamo's page and the card statement, before the session name.
     */
    titlePrefix?: string | null;
    captureNote?: string | null;
  };
  reconciliation?: {
    /**
     * Catches a payment whose webhook never arrived.
     */
    enabled?: boolean | null;
    /**
     * The checker wakes every minute and runs when this long has passed since the last run.
     */
    everyMinutes?: number | null;
    lastRunAt?: string | null;
    lastRunSummary?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Only if Mamo asks for it for Apple Pay on hosted links. Served as plain text at /.well-known/apple-developer-merchantid-domain-association. Leave empty otherwise.
   */
  appleDomainAssociation?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * How messages leave the server. The wording of each message is under Emails → Templates; the text printed on tickets is under Booking & checkout wording.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings".
 */
export interface EmailSetting {
  id: string;
  /**
   * Log only writes every message to the notification log and sends nothing. Customers will not receive confirmations, tickets or invoices, and staff cannot reset passwords, until a real provider is verified.
   */
  provider: 'log-only' | 'smtp' | 'resend';
  /**
   * e.g. Maison Palettia
   */
  fromName?: string | null;
  /**
   * Must be a sender the provider has verified.
   */
  fromAddress?: string | null;
  /**
   * Where a customer's reply lands. Defaults to the From address.
   */
  replyTo?: string | null;
  /**
   * Optional. Every outgoing email is copied here.
   */
  bcc?: string | null;
  smtp?: {
    host?: string | null;
    port?: number | null;
    /**
     * On for port 465. Off uses STARTTLS on 587.
     */
    secure?: boolean | null;
    user?: string | null;
    password?: string | null;
    passwordSetAt?: string | null;
  };
  /**
   * From resend.com → API Keys. Sending permission is enough.
   */
  resendApiKey?: string | null;
  resendApiKeySetAt?: string | null;
  /**
   * { ok, at, provider, message } from the last Verify connection. Bookings cannot open until ok is true.
   */
  lastVerify?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Legal name, TRN, VAT rate, numbering, PDF logo and fonts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-settings".
 */
export interface InvoiceSetting {
  id: string;
  /**
   * Defaults to Site details → Legal entity name on first save, then stays put.
   */
  legalName?: string | null;
  tradeLicenceNumber?: string | null;
  /**
   * 15 digits. Leave empty until registered: without it the PDF is a Receipt, with it a Tax Invoice.
   */
  trn?: string | null;
  /**
   * One line per row, as it should print under the legal name.
   */
  addressLines?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  issuerEmail?: string | null;
  issuerPhone?: string | null;
  /**
   * 500 = 5 %, the UAE standard rate. 0 switches VAT lines off.
   */
  vatRateBps: number;
  /**
   * On: AED 240 on the site means AED 240 paid, VAT carved out inside it.
   */
  pricesIncludeVat?: boolean | null;
  /**
   * Numbers run gapless per year: MP-INV-2026-000123.
   */
  invoicePrefix?: string | null;
  creditNotePrefix?: string | null;
  /**
   * Printed at the foot of every invoice: refund summary, thanks, bank details if any.
   */
  footerNote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leave empty to use Site details → Logo (dark cut).
   */
  logo?: (string | null) | Media;
  /**
   * TTF or OTF uploaded to Media. Used for invoice and ticket PDFs; Inter is the fallback when empty. No redeploy needed.
   */
  pdfFonts?: {
    regular?: (string | null) | Media;
    bold?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Which staff email receives which alert.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings".
 */
export interface NotificationSetting {
  id: string;
  /**
   * At least one person should receive New order, Failed payment, Refund requested, New enquiry and Background task failed.
   */
  recipients?:
    | {
        name?: string | null;
        email: string;
        /**
         * Everything ticked is emailed to this address.
         */
        events?:
          | (
              | 'new_order'
              | 'failed_payment'
              | 'refund_requested'
              | 'refund'
              | 'dispute'
              | 'new_enquiry'
              | 'waitlist_joined'
              | 'job_failed'
              | 'low_seats'
              | 'settings_changed'
              | 'webhook_unverified_spike'
              | 'daily_digest'
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to use the site threshold (Booking & checkout wording → “Few seats left” threshold).
   */
  lowSeatsOverride?: number | null;
  /**
   * Sends the “enquiry received” email to the person who wrote in (Emails → Templates).
   */
  enquiryAutoReply?: boolean | null;
  /**
   * Yesterday's orders, enquiries and problems in one email to everyone subscribed to Daily digest.
   */
  dailyDigest?: boolean | null;
  /**
   * 0–23. 8 means 08:00 Gulf Standard Time.
   */
  dailyDigestHour?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * First-party panel, optional GA4/Plausible/Umami/Meta, cookie consent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings".
 */
export interface AnalyticsSetting {
  id: string;
  /**
   * Cookieless and on this server only. Powers Analytics in the admin.
   */
  enabled?: boolean | null;
  /**
   * Skip visitors whose browser sends DNT.
   */
  respectDoNotTrack?: boolean | null;
  /**
   * Daily totals are kept forever; raw rows are purged after this many days.
   */
  rawRetentionDays?: number | null;
  /**
   * Checkout and account pages stay out of every chart. Query strings and #fragments are never sent anyway.
   */
  excludePaths?:
    | {
        /**
         * Starts with a slash, e.g. /checkout. A trailing * matches everything beneath.
         */
        path: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Public ids, not secrets. Scripts load only after the visitor accepts the consent banner.
   */
  external?: {
    provider?: ('none' | 'ga4' | 'plausible' | 'umami') | null;
    /**
     * Looks like G-XXXXXXXXXX.
     */
    measurementId?: string | null;
    /**
     * The site as registered in Plausible, e.g. maisonpalettia.com.
     */
    plausibleDomain?: string | null;
    /**
     * https://… on analytics.umami.is, cloud.umami.is or this site's own address.
     */
    umamiScriptUrl?: string | null;
    umamiWebsiteId?: string | null;
    /**
     * Digits only. Leave empty for no pixel. Loads only after consent, like the provider above.
     */
    metaPixelId?: string | null;
  };
  /**
   * Shown once; the choice is remembered in the visitor's browser.
   */
  consent: {
    /**
     * Required under UAE data protection rules. The first-party panel never needs consent.
     */
    required?: boolean | null;
    bannerText?: string | null;
    acceptLabel?: string | null;
    declineLabel?: string | null;
    policyLink: {
      type: 'internal' | 'external';
      url?: string | null;
      /**
       * Scrolls to a section, e.g. scheduled → /events#scheduled
       */
      anchor?: string | null;
      newTab?: boolean | null;
    };
  };
  dashboard?: {
    defaultRange?: ('7' | '30' | '90') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-state".
 */
export interface SystemState {
  id: string;
  /**
   * Sealed “ok”, opened on every boot to prove PAYLOAD_SECRET still matches the stored secrets.
   */
  canary?: string | null;
  canarySetAt?: string | null;
  installedAt?: string | null;
  /**
   * The version of cms/seed last applied; the seed uses it to decide what to upgrade.
   */
  seedVersion?: string | null;
  publicUrlConfirmedAt?: string | null;
  lastDigestDay?: string | null;
  lastInventoryReconcileAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  tagline?: T;
  logoOnDark?: T;
  logoOnDarkInk?:
    | T
    | {
        left?: T;
        top?: T;
        width?: T;
        height?: T;
      };
  logoOnLight?: T;
  monogram?: T;
  contact?:
    | T
    | {
        addressLines?:
          | T
          | {
              line?: T;
              id?: T;
            };
        email?: T;
        phone?: T;
        whatsappNumber?: T;
        whatsappGreeting?: T;
        hours?:
          | T
          | {
              days?: T;
              hours?: T;
              id?: T;
            };
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  newsletter?:
    | T
    | {
        enabled?: T;
        actionUrl?: T;
        fieldName?: T;
        heading?: T;
        description?: T;
        cta?: T;
      };
  publicUrl?: T;
  locale?: T;
  heroTheme?:
    | T
    | {
        darkRoutes?:
          | T
          | {
              path?: T;
              id?: T;
            };
        lightRoutes?:
          | T
          | {
              path?: T;
              id?: T;
            };
      };
  enquiriesEnabled?: T;
  jobsEnabled?: T;
  allowAiImagery?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
        menu?: T;
        mobileSurface?: T;
        mobileShortLabel?: T;
        secondary?: T;
        utility?: T;
        id?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
      };
  bottomBar?:
    | T
    | {
        contactLabel?: T;
        aboutLabel?: T;
        bookLabel?: T;
      };
  bookSheet?:
    | T
    | {
        heading?: T;
        lead?: T;
        anytimeNote?: T;
        anytimeLinkLabel?: T;
      };
  skipLink?: T;
  experiencesMenu?:
    | T
    | {
        groups?:
          | T
          | {
              kind?: T;
              title?: T;
              note?: T;
              id?: T;
            };
        door?:
          | T
          | {
              title?: T;
              sub?: T;
              link?:
                | T
                | {
                    type?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
            };
        previewActionDiy?: T;
        previewActionScheduled?: T;
      };
  privateEventsMenu?:
    | T
    | {
        railTitle?: T;
        railNote?: T;
        previewEyebrow?: T;
        previewAction?: T;
        doors?:
          | T
          | {
              title?: T;
              sub?: T;
              link?:
                | T
                | {
                    type?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              accent?: T;
              id?: T;
            };
      };
  aboutMenu?:
    | T
    | {
        doors?:
          | T
          | {
              name?: T;
              sub?: T;
              link?:
                | T
                | {
                    type?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              mark?: T;
              id?: T;
            };
      };
  mobile?:
    | T
    | {
        privateEventsCta?: T;
      };
  footer?:
    | T
    | {
        groups?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        findUsHeading?: T;
        studioHeading?: T;
        whyHeading?: T;
        followHeading?: T;
        policiesHeading?: T;
        directionsLabel?: T;
        policiesBlurb?: T;
        backToTop?: T;
      };
  legal?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
        id?: T;
      };
  utilityBar?:
    | T
    | {
        heading?: T;
      };
  search?:
    | T
    | {
        triggerLabel?: T;
        heading?: T;
        placeholderWide?: T;
        placeholderNarrow?: T;
        popularHeading?: T;
        sessionsHeading?: T;
        activitiesHeading?: T;
        viewAllLabel?: T;
        noResultsTitle?: T;
        noResultsBody?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-copy_select".
 */
export interface BrandCopySelect<T extends boolean = true> {
  tagline?: T;
  brandStory?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  openingStatement?:
    | T
    | {
        heading?: T;
        body?: T;
        closer?: T;
        panel?:
          | T
          | {
              heading?: T;
              body?: T;
              signOff?: T;
            };
      };
  closing?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  mission?: T;
  vision?: T;
  purposeLabels?:
    | T
    | {
        mission?: T;
        vision?: T;
      };
  community?:
    | T
    | {
        heading?: T;
        body?: T;
        closer?: T;
      };
  journey?:
    | T
    | {
        slug?: T;
        name?: T;
        description?: T;
        id?: T;
      };
  whatSetsUsApart?:
    | T
    | {
        slug?: T;
        name?: T;
        description?: T;
        id?: T;
      };
  findUsHeading?: T;
  findUsLine?: T;
  makeItYourWay?: T;
  privateEventInvite?: T;
  programmesNote?: T;
  everythingProvided?: T;
  privateEventSteps?:
    | T
    | {
        title?: T;
        detail?: T;
        id?: T;
      };
  seasonalIntro?: T;
  seasonalMoments?:
    | T
    | {
        occasion?: T;
        experience?: T;
        image?: T;
        id?: T;
      };
  littleCreators?:
    | T
    | {
        name?: T;
        image?: T;
        id?: T;
      };
  collaborations?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  experienceStatement?: T;
  ourApproach?:
    | T
    | {
        line?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings_select".
 */
export interface BookingSettingsSelect<T extends boolean = true> {
  bookingsOpen?: T;
  closedMessage?: T;
  closedCtaLabel?: T;
  closedCtaLink?:
    | T
    | {
        type?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
      };
  bookingTerms?: T;
  referencePrefix?: T;
  lowSeatThreshold?: T;
  statusCopy?:
    | T
    | {
        confirmed?:
          | T
          | {
              label?: T;
              note?: T;
            };
        pending?:
          | T
          | {
              label?: T;
              note?: T;
            };
        completed?:
          | T
          | {
              label?: T;
              note?: T;
            };
        cancelled?:
          | T
          | {
              label?: T;
              note?: T;
            };
      };
  purchaseConfirmedNote?: T;
  checkout?:
    | T
    | {
        heading?: T;
        backLabel?: T;
        detailsHeading?: T;
        detailsLead?: T;
        carriedOverNote?: T;
        confirmLabel?: T;
        confirmingLabel?: T;
        emptyTitle?: T;
        emptyBody?: T;
        emptyCta?: T;
        errorGeneric?: T;
        errorEmpty?: T;
        errorPassed?: T;
        errorFields?: T;
      };
  cart?:
    | T
    | {
        heading?: T;
        addAnother?: T;
        removeLabel?: T;
        passedLine?: T;
        subtotalLabel?: T;
        totalLabel?: T;
      };
  basketLinkLabel?: T;
  passCodeCopy?:
    | T
    | {
        label?: T;
        placeholder?: T;
        apply?: T;
        messages?:
          | T
          | {
              empty?: T;
              unavailable?: T;
              invalid?: T;
              applied?: T;
            };
      };
  bookStep?:
    | T
    | {
        heading?: T;
        lead?: T;
        backLabel?: T;
        steps?:
          | T
          | {
              label?: T;
              id?: T;
            };
        continueLabel?: T;
        openingLabel?: T;
        summaryError?: T;
        notesLabel?: T;
        passedTitle?: T;
        passedBody?: T;
        passedCta?: T;
      };
  confirmation?:
    | T
    | {
        heading?: T;
        viewEventsLabel?: T;
        checkStatusLabel?: T;
        notFoundHeading?: T;
        notFoundTitle?: T;
        notFoundBodyWithRef?: T;
        notFoundBodyNoRef?: T;
      };
  status?:
    | T
    | {
        heading?: T;
        lead?: T;
        fieldLabel?: T;
        placeholder?: T;
        hint?: T;
        cta?: T;
        noneTitle?: T;
        noneBody?: T;
        noneCta?: T;
      };
  eventPage?:
    | T
    | {
        bookLabel?: T;
        passedLabel?: T;
        perPersonLabel?: T;
        closedFullFact?: T;
        closedPassedFact?: T;
        noneOpenSuffix?: T;
        othersOpenSuffix?: T;
        seeOpenLabel?: T;
        diyTitle?: T;
        diyBody?: T;
        diyCta?: T;
        comingSoonNote?: T;
        readyHeading?: T;
        readyBody?: T;
        utilityNote?: T;
      };
  labels?:
    | T
    | {
        createAnytime?: T;
        createTogether?: T;
        anyTime?: T;
        scheduled?: T;
        noBooking?: T;
        bookedOnline?: T;
        scheduledSession?: T;
        diyLine?: T;
        scheduledLine?: T;
      };
  utilityBars?:
    | T
    | {
        eventDetail?:
          | T
          | {
              note?: T;
              links?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
            };
        checkout?:
          | T
          | {
              note?: T;
              links?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
            };
      };
  ticket?:
    | T
    | {
        heading?: T;
        instructions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "template-copy_select".
 */
export interface TemplateCopySelect<T extends boolean = true> {
  eventDetail?:
    | T
    | {
        breadcrumbRoot?: T;
        whenTerm?: T;
        timeTerm?: T;
        durationTerm?: T;
        whereTerm?: T;
        priceTerm?: T;
        perPersonLabel?: T;
        howItRunsTerm?: T;
        statusTerm?: T;
        aboutHeading?: T;
        locationHeadingScheduled?: T;
        locationHeadingDiy?: T;
        directionsNote?: T;
        moreEventsHeading?: T;
        soloEyebrow?: T;
        soloCta?: T;
        upcomingDatesHeading?: T;
        waitlistHeading?: T;
        waitlistBody?: T;
        waitlistCta?: T;
        waitlistSuccess?: T;
      };
  programmeDetail?:
    | T
    | {
        eyebrow?: T;
        activitiesHeading?: T;
        activitiesLead?: T;
        stepsEyebrow?: T;
        closeHeading?: T;
        ctaPrimaryLabel?: T;
        ctaSecondaryLabel?: T;
      };
  policyDetail?:
    | T
    | {
        eyebrow?: T;
        backLabel?: T;
        closeHeading?: T;
        closeBody?: T;
        closeCta?: T;
      };
  eventsBrowser?:
    | T
    | {
        dateFilterLabel?: T;
        typeFilterLabel?: T;
        locationFilterLabel?: T;
        clearFilterLabel?: T;
        clearAllLabel?: T;
        emptyTitle?: T;
        emptyBody?: T;
        doorModeLabels?:
          | T
          | {
              diy?: T;
              scheduled?: T;
            };
        datePassedLabel?: T;
        fullyBookedLabel?: T;
      };
  notFound?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        cta?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  titleTemplate?: T;
  shareImage?: T;
  twitterCard?: T;
  robotsDisallow?:
    | T
    | {
        path?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-settings_select".
 */
export interface PaymentSettingsSelect<T extends boolean = true> {
  mode?: T;
  provider?: T;
  test?:
    | T
    | {
        apiKey?: T;
        apiKeySetAt?: T;
        webhookAuthHeader?: T;
        webhookAuthHeaderSetAt?: T;
        previousWebhookAuthHeader?: T;
        previousWebhookAuthHeaderSetAt?: T;
        previousValidUntil?: T;
        webhookId?: T;
        webhookRegisteredAt?: T;
        webhookUrl?: T;
        lastConnectionCheck?: T;
        observedAuthHeaderName?: T;
      };
  live?:
    | T
    | {
        apiKey?: T;
        apiKeySetAt?: T;
        webhookAuthHeader?: T;
        webhookAuthHeaderSetAt?: T;
        previousWebhookAuthHeader?: T;
        previousWebhookAuthHeaderSetAt?: T;
        previousValidUntil?: T;
        webhookId?: T;
        webhookRegisteredAt?: T;
        webhookUrl?: T;
        lastConnectionCheck?: T;
        observedAuthHeaderName?: T;
      };
  checkout?:
    | T
    | {
        linkType?: T;
        paymentMethods?: T;
        enableTabby?: T;
        sendMamoReceipt?: T;
        requireTerms?: T;
        holdMinutes?: T;
        titlePrefix?: T;
        captureNote?: T;
      };
  reconciliation?:
    | T
    | {
        enabled?: T;
        everyMinutes?: T;
        lastRunAt?: T;
        lastRunSummary?: T;
      };
  appleDomainAssociation?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-settings_select".
 */
export interface EmailSettingsSelect<T extends boolean = true> {
  provider?: T;
  fromName?: T;
  fromAddress?: T;
  replyTo?: T;
  bcc?: T;
  smtp?:
    | T
    | {
        host?: T;
        port?: T;
        secure?: T;
        user?: T;
        password?: T;
        passwordSetAt?: T;
      };
  resendApiKey?: T;
  resendApiKeySetAt?: T;
  lastVerify?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-settings_select".
 */
export interface InvoiceSettingsSelect<T extends boolean = true> {
  legalName?: T;
  tradeLicenceNumber?: T;
  trn?: T;
  addressLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  issuerEmail?: T;
  issuerPhone?: T;
  vatRateBps?: T;
  pricesIncludeVat?: T;
  invoicePrefix?: T;
  creditNotePrefix?: T;
  footerNote?: T;
  logo?: T;
  pdfFonts?:
    | T
    | {
        regular?: T;
        bold?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings_select".
 */
export interface NotificationSettingsSelect<T extends boolean = true> {
  recipients?:
    | T
    | {
        name?: T;
        email?: T;
        events?: T;
        id?: T;
      };
  lowSeatsOverride?: T;
  enquiryAutoReply?: T;
  dailyDigest?: T;
  dailyDigestHour?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings_select".
 */
export interface AnalyticsSettingsSelect<T extends boolean = true> {
  enabled?: T;
  respectDoNotTrack?: T;
  rawRetentionDays?: T;
  excludePaths?:
    | T
    | {
        path?: T;
        id?: T;
      };
  external?:
    | T
    | {
        provider?: T;
        measurementId?: T;
        plausibleDomain?: T;
        umamiScriptUrl?: T;
        umamiWebsiteId?: T;
        metaPixelId?: T;
      };
  consent?:
    | T
    | {
        required?: T;
        bannerText?: T;
        acceptLabel?: T;
        declineLabel?: T;
        policyLink?:
          | T
          | {
              type?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
      };
  dashboard?:
    | T
    | {
        defaultRange?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-state_select".
 */
export interface SystemStateSelect<T extends boolean = true> {
  canary?: T;
  canarySetAt?: T;
  installedAt?: T;
  seedVersion?: T;
  publicUrlConfirmedAt?: T;
  lastDigestDay?: T;
  lastInventoryReconcileAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNoop".
 */
export interface TaskNoop {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}