import { sql, type SQL } from "@payloadcms/db-postgres/drizzle";
import { commitTransaction, initTransaction, killTransaction, type Field, type PayloadRequest, type TaskConfig, type WorkflowConfig } from "payload";

import { getPaymentGateway, notifyStaff, publicUrl, type JobInputs, type Mode, type PaymentGateway } from "@/cms/lib/contracts";

import { AlertThrottle, isFinalFailure, scrubError } from "./logic";

/**
 * ==========================================================================
 * What every background job shares — plumbing for cms/jobs/tasks/* (§H.9)
 * ==========================================================================
 *
 * Four pieces, each small:
 *
 *   · `defineTask` — turns a task spec into a Payload `TaskConfig` with the
 *     house rules attached: typed input from `JobInputs` (cms/lib/contracts),
 *     a concurrency key, retries, and the final-failure alert. Every task in
 *     this folder is written with it, so the rules cannot be forgotten on one.
 *   · the final-failure alert — Payload calls `onFail` on EVERY failure,
 *     retries included; `isFinalFailure` (logic.ts) decides which one is the
 *     last, and only that one emails staff (`notifyStaff("job_failed")`),
 *     throttled so an SMTP outage is one email an hour, not hundreds. A
 *     failure that is itself a staff email only logs (it could not be
 *     delivered anyway, and must not loop).
 *   · `enqueue` — queues a task or workflow by its `JobInputs` name, on the
 *     right queue (emails on `email`), without depending on the generated
 *     `TypedJobs` (payload-types.ts is regenerated by 3A-1 after this lands).
 *   · `runSql` / `inTransaction` — raw statements through drizzle's `sql`
 *     tag only (values are bind parameters, never concatenated), joined to
 *     the transaction on `req` when there is one.
 *
 * WHO CALLS WHAT. Jobs reach other agents' code (orders, gateway, email,
 * tickets) only through `@/cms/lib/contracts`; the SQL here touches only
 * rows the jobs own the timing of (holds, claims, stamps). Enum values in
 * SQL are written as literals in the template, never as parameters:
 * Postgres will not compare an enum column with a text parameter.
 */

export type JobSlug = keyof JobInputs;

type Retries = TaskConfig["retries"];
type Schedule = NonNullable<TaskConfig["schedule"]>;
export type JobLike = { id: string | number; totalTried?: number | null; workflowSlug?: string | null; concurrencyKey?: string | null };

/* ────────────────────────────────────────────────────────────────────────── */
/* Queues                                                                     */
/* ────────────────────────────────────────────────────────────────────────── */

/** `email` is polled every 20 s (a customer is waiting for a ticket); everything else every minute. */
export const QUEUE_OF: Partial<Record<JobSlug, "email" | "default">> = {
  "send-email": "email",
  "send-daily-digest": "email",
};

export const WORKFLOW_SLUGS: ReadonlySet<JobSlug> = new Set<JobSlug>(["finalize-order"]);

/**
 * Queues a job by name. Returns the job id, or null when the slug is not
 * registered in this build (so a caller running before a deploy that adds
 * the task degrades to "not queued" instead of an enum violation that
 * would abort its transaction).
 */
export async function enqueue<K extends JobSlug>(req: PayloadRequest, slug: K, input: JobInputs[K], opts: { waitUntil?: Date } = {}): Promise<string | null> {
  const isWorkflow = WORKFLOW_SLUGS.has(slug);
  const jobs = req.payload.config.jobs as { tasks?: Array<{ slug: string }>; workflows?: Array<{ slug: string }> } | undefined;
  const registered = (isWorkflow ? jobs?.workflows : jobs?.tasks)?.some((entry) => entry.slug === slug) ?? false;
  if (!registered) {
    req.payload.logger.warn(`jobs: "${slug}" is not registered in this build; not queued`);
    return null;
  }
  // Cast: `payload.jobs.queue` is typed from the generated `TypedJobs`, which only
  // knows these slugs after `generate:types`; `JobInputs` is the source of truth.
  const queue = req.payload.jobs.queue as unknown as (args: Record<string, unknown>) => Promise<{ id: string | number }>;
  const job = await queue({
    ...(isWorkflow ? { workflow: slug } : { task: slug }),
    input,
    queue: QUEUE_OF[slug] ?? "default",
    req,
    ...(opts.waitUntil ? { waitUntil: opts.waitUntil } : {}),
  });
  return job?.id !== undefined ? String(job.id) : null;
}

/* ────────────────────────────────────────────────────────────────────────── */
/* SQL                                                                        */
/* ────────────────────────────────────────────────────────────────────────── */

type Executor = { execute: (query: SQL) => Promise<unknown> };
type AdapterLike = {
  drizzle: Executor;
  sessions?: Record<string, { db: Executor } | undefined>;
  execute: (args: { db?: Executor; drizzle?: Executor; sql: SQL }) => Promise<unknown>;
};

/** The drizzle handle of the transaction on `req`, or the pool when there is none. */
async function txDb(req: PayloadRequest): Promise<Executor> {
  const adapter = req.payload.db as unknown as AdapterLike;
  const id = req.transactionID ? await req.transactionID : undefined;
  return (id !== undefined && adapter.sessions?.[String(id)]?.db) || adapter.drizzle;
}

/** One statement, inside `req`'s transaction when there is one; returns the rows. */
export async function runSql<Row extends Record<string, unknown> = Record<string, unknown>>(req: PayloadRequest, query: SQL): Promise<Row[]> {
  const adapter = req.payload.db as unknown as AdapterLike;
  const result = (await adapter.execute({ db: await txDb(req), sql: query })) as { rows?: Row[] } | Row[] | undefined;
  if (Array.isArray(result)) return result;
  return result?.rows ?? [];
}

/**
 * Runs `fn` in a transaction on `req`: joins one the caller already opened,
 * otherwise opens one, commits on success and rolls back on any throw. Each
 * item a sweep handles gets its own, so one bad row never undoes the rest.
 */
export async function inTransaction<T>(req: PayloadRequest, fn: () => Promise<T>): Promise<T> {
  const owner = await initTransaction(req);
  try {
    const result = await fn();
    if (owner) await commitTransaction(req);
    return result;
  } catch (error) {
    if (owner) await killTransaction(req);
    throw error;
  }
}

export { sql };

/* ────────────────────────────────────────────────────────────────────────── */
/* Small reads every job needs                                                */
/* ────────────────────────────────────────────────────────────────────────── */

/** A settings global as the server sees it (no access checks; secrets stay masked). */
export async function readSettings<T extends Record<string, unknown>>(req: PayloadRequest, slug: string): Promise<Partial<T>> {
  try {
    // Deliberately no `req` and no `context`: Payload merges a call's context
    // into the request it is given, and a flag such as `internalRead` left on
    // the job's request would reveal secrets to every later read in the job.
    const doc = await req.payload.findGlobal({ slug: slug as never, depth: 0, overrideAccess: true });
    return (doc ?? {}) as Partial<T>;
  } catch (error) {
    req.payload.logger.warn(`jobs: could not read ${slug}: ${scrubError(error)}`);
    return {};
  }
}

/** Absolute admin link for staff emails, e.g. adminLink(req, "collections/orders/abc"). */
export async function adminLink(req: PayloadRequest, path: string): Promise<string> {
  const base = (await publicUrl(req).catch(() => "")) || "";
  return `${base}/admin/${path.replace(/^\/+/, "")}`;
}

/**
 * The gateway that can act on a row minted in `mode`, or null. A row is only
 * ever handled by the gateway of its own mode (§H.5 step 7: a sandbox event
 * can never touch a live order, or the reverse): test/live rows ask for that
 * mode explicitly; mock rows use the default gateway, which is the mock
 * only while Payments is in Mock mode (or has no key) outside production.
 */
export async function gatewayFor(req: PayloadRequest, mode: Mode | null | undefined): Promise<PaymentGateway | null> {
  if (mode !== "test" && mode !== "live" && mode !== "mock") return null;
  const gateway = mode === "mock" ? await getPaymentGateway(req) : await getPaymentGateway(req, { forceMode: mode });
  if (!gateway.isConfigured || gateway.mode !== mode) return null;
  return gateway;
}

/** Duck-typed `MamoApiError` (status + messages), so the check survives a re-export or a second copy of the class. */
export function mamoErrorStatus(error: unknown): number | undefined {
  if (!error || typeof error !== "object") return undefined;
  const e = error as { status?: unknown; messages?: unknown };
  return typeof e.status === "number" && Array.isArray(e.messages) ? e.status : undefined;
}

/** A relationship value (id or populated doc) as an id string. */
export function idOf(value: unknown): string | null {
  if (value === null || value === undefined || value === "") return null;
  if (typeof value === "string" || typeof value === "number") return String(value);
  if (typeof value === "object" && "id" in (value as Record<string, unknown>)) return idOf((value as { id: unknown }).id);
  return null;
}

/* ────────────────────────────────────────────────────────────────────────── */
/* Failure handling                                                           */
/* ────────────────────────────────────────────────────────────────────────── */

/**
 * The error a handler threw, by job + task, so `onFail` (which Payload calls
 * without the error) can put the reason in the staff email. Entries are
 * consumed by the next `onFail` for the same job and task.
 */
const lastErrors = new Map<string, { message: string; logOnly: boolean }>();
const errorKey = (jobId: string | number, slug: string) => `${String(jobId)}:${slug}`;

/** Marks an error as "log, do not email staff" — for failures that ARE staff emails. */
export function logOnly<E>(error: E): E {
  if (error && typeof error === "object") (error as { mpLogOnly?: boolean }).mpLogOnly = true;
  return error;
}

const throttle = new AlertThrottle(60 * 60_000);

/** Alert-key granularity: per job for money paths, per task for high-volume or periodic ones. */
export type AlertScope = "job" | "task" | "never";

export const attemptsOf = (retries: Retries | WorkflowConfig["retries"]): number | undefined => {
  if (retries === undefined || retries === null) return undefined;
  if (typeof retries === "number") return retries;
  return typeof retries.attempts === "number" ? retries.attempts : undefined;
};

/**
 * The final-failure alert itself: log it and, unless the scope is "never"
 * or the error was marked `logOnly`, email staff through
 * `notifyStaff("job_failed")`, at most once an hour per key. Best-effort: if
 * the alert cannot be sent, the job row in the admin (System → Background
 * jobs, with Retry) still shows the failure.
 */
export async function alertFinalFailure(args: {
  req: PayloadRequest;
  job: JobLike;
  slug: string;
  label: string;
  message: string;
  logOnly?: boolean;
  scope: AlertScope;
  refs?: Record<string, string>;
}): Promise<void> {
  const { req, job, slug } = args;
  req.payload.logger.error({ msg: `jobs: ${slug} failed for the last time`, jobId: String(job.id), taskSlug: slug, error: args.message });
  if (args.scope === "never" || args.logOnly) return;
  const key = args.scope === "job" ? `${slug}:${String(job.id)}` : slug;
  if (!throttle.take(key)) return;
  try {
    await notifyStaff(
      req,
      "job_failed",
      {
        task: args.label,
        taskSlug: slug,
        jobId: String(job.id),
        attempts: (job.totalTried ?? 0) + 1,
        error: args.message,
        links: { admin: await adminLink(req, `collections/payload-jobs/${String(job.id)}`) },
      },
      args.refs ?? {},
    );
  } catch (error) {
    req.payload.logger.error({ msg: `jobs: could not alert staff about ${slug}`, jobId: String(job.id), error: scrubError(error) });
  }
}

/** The attempts a workflow allows (its `retries`), for tasks that inherit them. */
export function workflowAttempts(req: PayloadRequest, job: JobLike): number | undefined {
  const workflowSlug = job.workflowSlug ?? undefined;
  const workflow = workflowSlug ? req.payload.config.jobs?.workflows?.find((w) => w.slug === workflowSlug) : undefined;
  return attemptsOf(workflow?.retries);
}

/**
 * `onFail` for a task. Payload calls it on EVERY failure (and without the
 * error), so it reads the message the handler stashed and alerts only when
 * `isFinalFailure` says this was the last attempt.
 */
function finalFailureAlert(slug: string, label: string, retries: Retries, scope: AlertScope, refsOf?: (input: Record<string, unknown>) => Record<string, string>) {
  return async ({ input, job, req, taskStatus }: { input?: object; job: JobLike; req: PayloadRequest; taskStatus: { totalTried?: number } | null }) => {
    const stashed = lastErrors.get(errorKey(job.id, slug));
    lastErrors.delete(errorKey(job.id, slug));
    const final = isFinalFailure({
      taskAttempts: attemptsOf(retries),
      workflowAttempts: workflowAttempts(req, job),
      taskTriedBefore: taskStatus?.totalTried ?? 0,
      jobTriedBefore: job.totalTried ?? 0,
      inWorkflow: Boolean(job.workflowSlug),
    });
    if (!final) return;
    await alertFinalFailure({
      req,
      job,
      slug,
      label,
      message: stashed?.message ?? "The task failed (no message).",
      logOnly: stashed?.logOnly,
      scope,
      refs: refsOf?.((input ?? {}) as Record<string, unknown>),
    });
  };
}

/* ────────────────────────────────────────────────────────────────────────── */
/* defineTask                                                                 */
/* ────────────────────────────────────────────────────────────────────────── */

export interface TaskSpec<K extends JobSlug, O extends object> {
  slug: K;
  label: string;
  /** Retries per §H.9. A number, or `{ attempts, backoff }`. */
  retries: Retries;
  /** §H.9: a fixed key for sweeps (one at a time), a per-entity key for per-order/payment/session work. */
  concurrency: (args: { input: JobInputs[K]; queue: string }) => string;
  /** Fixed crons (§H.9) — queued by the autoRun tick of `queue`. */
  schedule?: Schedule;
  /** Only for the generated `TypedJobs` types; Payload does not validate input against it. */
  inputSchema?: Field[];
  alert: AlertScope;
  /** Refs for the staff alert (e.g. `{ order: input.orderId }`). */
  alertRefs?: (input: JobInputs[K]) => Record<string, string>;
  run: (args: { input: JobInputs[K]; req: PayloadRequest; job: JobLike }) => Promise<O>;
}

/** The loose shape every task is registered with (`JobsConfig.tasks` takes `TaskConfig<any>[]`). */
type AnyTask = TaskConfig<{ input: object; output: object }>;

/**
 * A Payload task from a spec, with the house rules (see the header). The
 * spec is typed precisely from `JobInputs`; the returned config is the loose
 * form Payload registers (its generics resolve against the generated
 * `TypedJobs`, which cannot be named generically here).
 */
export function defineTask<K extends JobSlug, O extends object>(spec: TaskSpec<K, O>): AnyTask {
  const handler: AnyTask["handler"] = async ({ input, req, job }) => {
    try {
      const output = await spec.run({ input: (input ?? {}) as JobInputs[K], req, job: job as unknown as JobLike });
      return { output };
    } catch (error) {
      lastErrors.set(errorKey((job as unknown as JobLike).id, spec.slug), {
        message: scrubError(error),
        logOnly: Boolean(error && typeof error === "object" && (error as { mpLogOnly?: boolean }).mpLogOnly),
      });
      throw error;
    }
  };
  return {
    slug: spec.slug,
    label: spec.label,
    retries: spec.retries,
    concurrency: ((args: { input: object; queue: string }) => spec.concurrency({ input: args.input as JobInputs[K], queue: args.queue })) as AnyTask["concurrency"],
    ...(spec.schedule ? { schedule: spec.schedule } : {}),
    ...(spec.inputSchema ? { inputSchema: spec.inputSchema } : {}),
    handler,
    onFail: finalFailureAlert(
      spec.slug,
      spec.label,
      spec.retries,
      spec.alert,
      spec.alertRefs ? (input) => spec.alertRefs!(input as JobInputs[K]) : undefined,
    ) as unknown as AnyTask["onFail"],
  };
}

/** The schedule entry for a fixed cron on a queue (§H.9 table). */
export const cron = (expression: string, queue: "default" | "email" = "default"): Schedule => [{ cron: expression, queue }];

/** Sweeps return this shape so the admin's job log shows what happened at a glance. */
export interface SweepOutput {
  [key: string]: unknown;
  failures: Array<{ id: string; error: string }>;
}

/**
 * Per-item error capture for sweeps: an item that fails is logged and
 * listed in the job output, and the sweep carries on with the next one.
 */
export async function eachItem<T>(
  req: PayloadRequest,
  items: readonly T[],
  idOfItem: (item: T) => string,
  fn: (item: T) => Promise<void>,
  failures: SweepOutput["failures"],
): Promise<number> {
  let done = 0;
  for (const item of items) {
    try {
      await fn(item);
      done += 1;
    } catch (error) {
      const message = scrubError(error);
      failures.push({ id: idOfItem(item), error: message });
      req.payload.logger.error({ msg: "jobs: item failed", item: idOfItem(item), error: message });
    }
  }
  return done;
}

/**
 * A sweep that finished with item failures still SUCCEEDS (so one bad row
 * does not turn every minute into a failed job), but staff hear about it,
 * once an hour per task, with the job's own output as the detail.
 */
export async function reportSweepFailures(req: PayloadRequest, slug: JobSlug, label: string, job: JobLike, failures: SweepOutput["failures"]): Promise<void> {
  if (failures.length === 0 || !throttle.take(`${slug}:items`)) return;
  try {
    await notifyStaff(req, "job_failed", {
      task: label,
      taskSlug: slug,
      jobId: String(job.id),
      error: `${failures.length} item(s) failed — first: ${failures[0].error}`,
      items: failures.slice(0, 10),
      links: { admin: await adminLink(req, `collections/payload-jobs/${String(job.id)}`) },
    });
  } catch (error) {
    req.payload.logger.error({ msg: `jobs: could not alert staff about ${slug} item failures`, error: scrubError(error) });
  }
}
